name: 'rust-audit-check'
description: 'Run cargo audit and check for security advisories'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  token:
    description: GitHub Actions token
    required: true
  generate-lockfile:
    description: Call 'cargo generate-lockfile' first
    required: false
    default: 'true'

runs:
  using: 'node12'
  main: 'dist/index.js'
